version: '2'

services:
  mongo:
    command: mongod
    image: mongo:3.2.0
    ports:
      - "27017:27017"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  redis:
    image: redis:3.0.7
    ports:
      - "6380:6379"
volumes:
  mongo-data:
    driver: local
